"""Mock data for hospitals, replacing Google Places API and Firecrawl Search."""

MOCK_HOSPITALS = [
    {
        "id": "hosp_1",
        "name": "St. Mary's Medical Center",
        "address": "1500 S Lake Park Ave, Chicago, IL 60615",
        "phone": "+1-312-555-0101",
        "distance_miles": 0.8,
        "rating": 4.3,
        "lat": 41.7900,
        "lng": -87.6025,
        "specialties": ["Emergency Medicine", "Cardiology", "Trauma Center Level II", "Stroke Center"],
        "er_wait_minutes": 25,
        "insurance_accepted": ["Blue Cross", "Aetna", "UnitedHealthcare", "Medicare", "Medicaid"],
        "hours": "24/7 Emergency",
        "firecrawl_summary": {
            "official_info": "Full-service hospital with 24/7 emergency department. 350-bed facility with Level II Trauma Center designation. Certified Primary Stroke Center.",
            "reviews_summary": "4.3 stars across 1,200+ reviews. Patients praise quick ER intake and friendly nursing staff. Some complaints about parking availability.",
            "notable_capabilities": ["Level II Trauma Center", "Primary Stroke Center", "Cardiac Catheterization Lab"],
            "recent_news": "Recently completed $50M expansion of emergency department, adding 30 new treatment bays.",
            "patient_sentiment": "Positive overall. Highly rated for emergency care speed and staff compassion.",
        },
    },
    {
        "id": "hosp_2",
        "name": "Lakefront General Hospital",
        "address": "2900 N Lakeshore Dr, Chicago, IL 60657",
        "phone": "+1-312-555-0202",
        "distance_miles": 1.2,
        "rating": 4.6,
        "lat": 41.7950,
        "lng": -87.5980,
        "specialties": ["Emergency Medicine", "Pediatrics", "Orthopedics", "Neurology"],
        "er_wait_minutes": 15,
        "insurance_accepted": ["Blue Cross", "Cigna", "UnitedHealthcare", "Medicare", "Humana"],
        "hours": "24/7 Emergency",
        "firecrawl_summary": {
            "official_info": "Teaching hospital affiliated with a major university. Known for pediatric emergency care and orthopedic surgery. 500-bed facility.",
            "reviews_summary": "4.6 stars across 2,500+ reviews. Exceptional pediatric care. Patients highlight short wait times and modern facilities.",
            "notable_capabilities": ["Pediatric ER", "Orthopedic Trauma", "Neurosurgery", "MRI/CT available 24/7"],
            "recent_news": "Named Top 10 Hospital in Illinois by U.S. News & World Report 2025.",
            "patient_sentiment": "Very positive. Parents especially recommend for children's emergencies. Clean, modern facility.",
        },
    },
    {
        "id": "hosp_3",
        "name": "Mercy Hospital & Health Center",
        "address": "700 W 68th St, Chicago, IL 60621",
        "phone": "+1-312-555-0303",
        "distance_miles": 2.1,
        "rating": 3.9,
        "lat": 41.7730,
        "lng": -87.6420,
        "specialties": ["Emergency Medicine", "Internal Medicine", "Burn Unit", "Psychiatry"],
        "er_wait_minutes": 40,
        "insurance_accepted": ["Medicaid", "Medicare", "Blue Cross", "Aetna", "Molina"],
        "hours": "24/7 Emergency",
        "firecrawl_summary": {
            "official_info": "Community hospital serving the South Side for over 100 years. Specialized burn unit — one of only 3 in the metro area. Comprehensive psychiatric emergency services.",
            "reviews_summary": "3.9 stars across 800+ reviews. Praised for burn care expertise and accepting all insurance. Some mention longer ER wait times during peak hours.",
            "notable_capabilities": ["Regional Burn Center", "Psychiatric Emergency Services", "Hyperbaric Medicine"],
            "recent_news": "Received state grant for community mental health outreach program expansion.",
            "patient_sentiment": "Mixed but improving. Burn unit rated excellent. ER can be crowded on weekends.",
        },
    },
    {
        "id": "hosp_4",
        "name": "Northwestern Memorial Hospital",
        "address": "251 E Huron St, Chicago, IL 60611",
        "phone": "+1-312-555-0404",
        "distance_miles": 3.5,
        "rating": 4.7,
        "lat": 41.8945,
        "lng": -87.6210,
        "specialties": ["Emergency Medicine", "Cardiology", "Oncology", "Transplant Surgery", "Trauma Center Level I"],
        "er_wait_minutes": 35,
        "insurance_accepted": ["Blue Cross", "Aetna", "UnitedHealthcare", "Cigna", "Medicare"],
        "hours": "24/7 Emergency",
        "firecrawl_summary": {
            "official_info": "Premier academic medical center and Level I Trauma Center. 900-bed facility with comprehensive specialty services. Magnet-designated nursing excellence.",
            "reviews_summary": "4.7 stars across 5,000+ reviews. Nationally ranked in multiple specialties. Patients note world-class care but higher costs.",
            "notable_capabilities": ["Level I Trauma Center", "Comprehensive Cancer Center", "Heart & Vascular Center", "Organ Transplant Program"],
            "recent_news": "Ranked #1 hospital in Illinois, #9 nationally by U.S. News 2025. New robotic surgery wing opened.",
            "patient_sentiment": "Excellent. Gold standard for complex cases. Worth the extra distance for serious conditions.",
        },
    },
    {
        "id": "hosp_5",
        "name": "Rush University Medical Center",
        "address": "1653 W Congress Pkwy, Chicago, IL 60612",
        "phone": "+1-312-555-0505",
        "distance_miles": 4.0,
        "rating": 4.5,
        "lat": 41.8748,
        "lng": -87.6690,
        "specialties": ["Emergency Medicine", "Neurology", "Orthopedics", "Pulmonology"],
        "er_wait_minutes": 20,
        "insurance_accepted": ["Blue Cross", "Aetna", "UnitedHealthcare", "Cigna", "Humana", "Medicare", "Medicaid"],
        "hours": "24/7 Emergency",
        "firecrawl_summary": {
            "official_info": "Academic medical center known for orthopedic and neurological care. Innovative butterfly-shaped building designed for efficiency. Accepts most major insurance plans.",
            "reviews_summary": "4.5 stars across 3,200+ reviews. Orthopedic department nationally ranked. Patients praise efficient triage and clear communication.",
            "notable_capabilities": ["Joint Replacement Center of Excellence", "Comprehensive Stroke Center", "Sleep Disorders Center", "Advanced Spine Center"],
            "recent_news": "Opened new outpatient orthopedic surgery center. Named best employer in healthcare by Forbes.",
            "patient_sentiment": "Very positive. Especially recommended for bone, joint, and neurological issues. Modern facility with good patient experience.",
        },
    },
]
